namespace Hulk;

// Esta es la clase que le va a dar las propiedades al token
enum Tipo_De_Token
{
    //tokens
    Numero,
    String,
    coma,
    Suma,
    Resta,
    Producto,
    Division,
    Potenciacion,
    Parentesis_Abierto,
    Parentesis_Cerrado,
    Bang,
    Igual,
    Implicacion,
    AmpersandAmpersand,
    PipePipe,
    Menor_que,
    Mayor_que,
    IgualIgual,
    Bang_Igual,
    Espacio,
    Malo,
    cierre,
    Final,
    Identificador,

    //Keywords
    True_Keyword,
    False_Keyword,
    if_Keyword,
    else_Keyword,
    print_Keyword,
    let_Keyword,
    in_Keyword,
    sen_Keyword,
    cos_Keyword,
    PI_Keyword,
    function_Keyword,
    logaritmo_Keyword,

    //Expresiones
    Parentesis,
    Expresion_Unaria,
    Expresion_Binaria,
    Literal,
    Variable,
    Asignacion,
    if_Expresion,
    else_Expresion,
    Print_Expresion,
    let_Expresion,
    in_Expresion,
    sen_Expresion,
    cos_Expresion,
    function_Expresion,
    coma_Expresion,
    parametros_Expresion,
    logaritmo_Expresion,

}